tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
checks:
    php:
        uppercase_constants: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        simplify_boolean_return: true
        return_doc_comments: true
        security_vulnerabilities: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        no_unnecessary_if: true
        missing_arguments: true
        code_rating: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_closing_tag: true
        argument_type_checks: true
        align_assignments: false
        duplication: false
filter:
    excluded_paths:
        - 'tests/*'
        - 'specs/*'
