language: php
before_script:
  - composer selfupdate
install:
  - composer install --prefer-source --no-interaction --dev -o
matrix:
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

script:
    - mkdir -p build/logs
    - vendor/bin/phpspec -n -v -f build/logs/clover.xml -b bin/bootstrap.php run

after_script:
    - php vendor/bin/coveralls -v
