language: php
before_script:
    - composer selfupdate
install:
    - composer install --prefer-source --no-interaction --optimize-autoloader
    - composer --dev --prefer-source --no-interaction require satooshi/php-coveralls:@dev
matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
    php:
        - 5.6
        - 5.5
        - 5.4
        - hhvm
script:
    - mkdir -p build
    - vendor/bin/phpspec --bootstrap=bootstrap.php --no-interaction --stop-on-failure run
after_script:
    - php vendor/bin/coveralls -v
