language: php
install:
  - composer selfupdate
  - composer install
matrix:
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

script:
    - phpunit --coverage-clover log/clover.xml

after_script:
    - php vendor/bin/coveralls -v
