language: php
before_script:
    - composer selfupdate
install:
    - composer install --prefer-source --no-interaction -o
matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
    php:
        - 5.6
        - 5.5
        - 5.4
        - hhvm
script:
    - mkdir -p logs
    - vendor/bin/phpspec -n --format=dot --bootstrap=bootstrap.php run

after_script:
    - php vendor/bin/coveralls -v
